### ISSUE TITLE
wfmash error with latest pggb build v0.1

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#95] opened 2021-05-05 01:58 UTC
Hi

I've just updated to the latest build and I'm now getting errors at the wfmash step aligning only small gene regions of a few thousand bp. I pulled the build from docker and set many of the parameters to the now recommended defaults (e.g. block_id_min=0). This has happened consistently with several different gene regions.

```
+ block_length=0
+ min_match_len=29
+ transclose_batch=10000000
+ block_weight_max=10000000
+ block_id_min=0
+ ratio_contain=0
+ path_jump_max=100
+ edge_jump_max=0
+ poa_params=1,4,6,2,26,1
+ segment_length=2000
+ srun -n 1 singularity exec --bind /data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp:/data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp /data/pggb_builds/pggb.sif pggb -i /data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/HORVU.MOREX.r2.3HG0222170_pan_genes_buffer-1000bp.fna -N -s 2000 -l 0 -p 85 -n 21 -k 29 -B 10000000 -w 10000000 -I 0 -R 0 -j 100 -e 0 -P 1,4,6,2,26,1 -t 16 -m -v -L -S -o pggb_output
[wfmash::map] Reference = [/data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/HORVU.MOREX.r2.3HG0222170_pan_genes_buffer-1000bp.fna]
[wfmash::map] Query = [/data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/HORVU.MOREX.r2.3HG0222170_pan_genes_buffer-1000bp.fna]
[wfmash::map] Kmer size = 16
[wfmash::map] Window size = 5
[wfmash::map] Segment length = 2000 (read split disabled)
[wfmash::map] Block length min = 0
[wfmash::map] Alphabet = DNA
[wfmash::map] Percentage identity threshold = 0.85%
[wfmash::map] Mapping output file = /data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/wfmash-H8TzOD
[wfmash::map] Filter mode = 1 (1 = map, 2 = one-to-one, 3 = none)
[wfmash::map] Execution threads  = 16
[wfmash::skch::Sketch::build] minimizers picked from reference = 20497
[wfmash::skch::Sketch::index] unique minimizers = 1415
[wfmash::skch::Sketch::computeFreqHist] Frequency histogram of minimizers = (1, 261) ... (27, 1)
[wfmash::skch::Sketch::computeFreqHist] With threshold 0.001%, consider all minimizers during lookup.
[wfmash::map] time spent computing the reference index: 0.00455175 sec
[wfmash::skch::Map::mapQuery] mapped 100.00% @ 2.44e+05 bp/s elapsed: 00:00:00:00 remain: 00:00:00:00
[wfmash::skch::Map::mapQuery] count of mapped reads = 21, reads qualified for mapping = 21, total input reads = 21, total input bp = 60984
[wfmash::map] time spent mapping the query: 2.63e-01 sec
[wfmash::map] mapping results saved in: /data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/wfmash-H8TzOD
[wfmash::align] Reference = [/data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/HORVU.MOREX.r2.3HG0222170_pan_genes_buffer-1000bp.fna]
[wfmash::align] Query = [/data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/HORVU.MOREX.r2.3HG0222170_pan_genes_buffer-1000bp.fna]
[wfmash::align] Mapping file = /data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/wfmash-H8TzOD
[wfmash::align] Alignment identity cutoff = 8.50e-01%
[wfmash::align] Alignment output file = /dev/stdout
[wfmash::align] time spent read the reference sequences: 2.53e-04 sec
Command terminated by signal 4
wfmash -X -s 2000 -l 0 -N -p 85 -n 21 -k 16 -t 16 /data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/HORVU.MOREX.r2.3HG0222170_pan_genes_buffer-1000bp.fna /data/pangene_graph_workflow/pangene-HORVU.MOREX.r2.3HG0222170_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/HORVU.MOREX.r2.3HG0222170_pan_genes_buffer-1000bp.fna
0.34s user 0.05s system 18% cpu 2.16s total 21224Kb max memory
srun: error: node-4: task 0: Exited with exit code 132
```

**Comment by ekg** [comment] 2021-05-05 07:23
I would suggest setting -s much higher (50-100kb) and -p closer to 2X the
nucleotide divergence. You appear to be running out of memory. The
alignment step is too difficult because of the very sensitive settings you
are using.

**Comment by ekg** [comment] 2021-05-05 07:24
Ah this is for just a single gene region.

Would you please share the FASTA? I can try to reproduce the issue.

**Comment by brettChapman** [comment] 2021-05-05 08:00
Hi Erik

Thanks. I've attached an example of one of the fasta files. Previously I was using a pggb version from a month or two ago, and these sequences aligned using wfmash back then. I used the same wfmash parameters back then as well. The only parameters I've now changed are the smoothxg parameters (e.g. block_id_min = 0).


[HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.zip](https://github.com/pangenome/pggb/files/6425690/HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.zip)

**Comment by ekg** [comment] 2021-05-05 08:17
Ok I'll check. We have some suspicion that the problem is with the build.
Are you using the docker image?

**Comment by brettChapman** [comment] 2021-05-05 08:20
Yeah I pulled the build from docker

**Comment by brettChapman** [comment] 2021-05-06 01:51
@ekg @subwaystation I can confirm that the new docker pull works. However I'm now not getting the parameters embedded in the file names, instead what looks like the version information (e.g. ba89602 for wfmash). Is this intentional? In the pggb script it still looks like its taking each parameter and naming the files accordingly. Thanks.

```
ls -lhtr pangene-HORVU.MOREX.r2.5HG0400750_mmseq2pctid-0.9_mmseq2mincov-0.8_pggb-mapping-pctid-85_geneBuffer-1000bp/pggb_output/
total 2.9M
-rw-rw-r-- 1 ubuntu ubuntu 1.1K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.05-06-2021_00:59:29.params.yml
-rw-rw-r-- 1 ubuntu ubuntu  66K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.wfmash.paf
-rw-rw-r-- 1 ubuntu ubuntu  34K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.seqwish.gfa
-rw-rw-r-- 1 ubuntu ubuntu  41K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.seqwish.gfa.prep.gfa
-rw-rw-r-- 1 ubuntu ubuntu 115K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.smooth.gfa
-rw-rw-r-- 1 ubuntu ubuntu 212K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.smooth.og
-rw-rw-r-- 1 ubuntu ubuntu  76K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.seqwish.og
-rw-rw-r-- 1 ubuntu ubuntu  330 May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.seqwish.og.stats
-rw-rw-r-- 1 ubuntu ubuntu  333 May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.smooth.og.stats
-rw-rw-r-- 1 ubuntu ubuntu 9.2K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.smooth.og.viz_mqc.png
-rw-rw-r-- 1 ubuntu ubuntu  38K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.smooth.og.lay
-rw-rw-r-- 1 ubuntu ubuntu  28K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.smooth.og.lay.draw.png
-rw-rw-r-- 1 ubuntu ubuntu 519K May  6 00:59 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.smooth.og.lay.draw_mqc.png
-rw-rw-r-- 1 ubuntu ubuntu 1.8M May  6 01:00 multiqc_report.html
drwxrwxr-x 2 ubuntu ubuntu 4.0K May  6 01:00 multiqc_data
-rw-rw-r-- 1 ubuntu ubuntu  15K May  6 01:00 HORVU.MOREX.r2.5HG0400750_pan_genes_buffer-1000bp.fna.ba89602.2ff309f.68f4dff.05-06-2021_00:59:29.log
```

**Comment by AndreaGuarracino** [comment] 2021-05-06 07:52
Hi @brettChapman, yes, that's intentional. This is a way to have a naming scheme still bound to the parameter inputs and a bit more polite with the names' length.

**Comment by subwaystation** [comment] 2021-07-19 14:14
@brettChapman got it to work ;)
So closing this one.

**Closed by subwaystation** 2021-07-19 14:14 UTC
