### ISSUE TITLE
Lack of alignment

### ISSUE THREAD

**Issue by jia-wu-feng** [pangenome/pggb#195] opened 2022-05-06 14:50 UTC
I used pggb for graph-based pangenome.

Some regions are disappearing from the alignment.

pggb -p 90 -s 100000 -n 18 -k 311 -o ${name}_90_10w -t 50 -T 40 -U -v -L -m -V FB19_011_3_pseudomolecules_v6_hap1:# -i ${name}.fa

![image](https://user-images.githubusercontent.com/24247803/167157229-f58a0da9-8db7-4594-9192-e3c9374c6d22.png)

**Comment by AndreaGuarracino** [comment] 2022-05-06 14:53
It seems you are not using the last `pggb` version. Can you update your installation and also try a smaller segment size?

**Comment by jia-wu-feng** [comment] 2022-05-10 11:44
> It seems you are not using the last `pggb` version. Can you update your installation and also try a smaller segment size?
@AndreaGuarracino 

Will the first output temp file contain all final alignment information?

I seem to have the same problem if they contain all the alignment blocks.  I also try a small segment size and a new version. The result is same.

But I try to use wfmash without -X is better, but it is still that some regions are no alignment. （Notably, they are assembled from haplotypes, and some regions are identical. ）



<img width="1406" alt="image" src="https://user-images.githubusercontent.com/24247803/167620434-d01152cf-9def-4f01-84df-f2695d24d171.png">

**Comment by ekg** [comment] 2022-05-10 12:19
This shouldn't happen.

Is it possible to share this test case so we can resolve the problem?

**Comment by jia-wu-feng** [comment] 2022-05-10 12:51
Yes, I will send the file to your gmail (erik.garrison@gmail.com). And you can download them.

**Comment by jia-wu-feng** [comment] 2022-05-10 12:51
@ekg

**Comment by AndreaGuarracino** [comment] 2022-05-11 13:17
It seems it is an over-filtering problem. By disabling the mapping filtering (`-f/--no-filter`), we get the missing mappings too:

```
wfmash Hordeum_bulbosum.fa.gz -t 48 -m -f > Hordeum_bulbosum.mappings.paf
pafplot Hordeum_bulbosum.mappings.paf
```

![Hordeum_bulbosum approx paf](https://user-images.githubusercontent.com/62253982/167859051-c79d8872-0734-4942-aceb-bea4cd75172c.png)

**Comment by AndreaGuarracino** [comment] 2022-05-11 13:54
A way to get that would be to specify a very `-n` value, but you would obtain a quite compressed/complex pangenome graph. This is likely to be a bug that we need to solve.

**Comment by jia-wu-feng** [comment] 2022-05-11 14:22
Thanks, I will try to use -f now. I look forward to the new version.

**Comment by ekg** [comment] 2022-05-12 08:56
We have an actual fix for this. It'll need to be merged in. https://github.com/ekg/wfmash/pull/134

**Closed** 2022-05-13 06:39 UTC

**Comment by ekg** [comment] 2022-10-11 07:44
You'll want to do the alignment independently and feed it into pggb -i.

This isn't ideal, but it can be a workaround for you to get started. I'd
expect to have a fix for this in the next few days.

The only filtering will be caused by wfmash -p -s and -l, so the graph will
have a kind of approximate a-bruijn quality to it, and it may be messy.
