### ISSUE TITLE
fatal error: ../include/wfmash_git_version.hpp: No such file or directory  

### ISSUE THREAD

**Issue by grenaud** [pangenome/pggb#150] opened 2022-01-06 10:12 UTC
Hello! I am trying to build the package but I get:
```

/home/ctools/wfmash/src/version.cpp:10:10: fatal error: ../include/wfmash_git_version.hpp: No such file or directory
   10 | #include "../include/wfmash_git_version.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by ekg** [comment] 2022-01-06 10:23
Is this via the docker build?

**Comment by grenaud** [comment] 2022-01-06 10:25
No via cmake

tor. d. 6. jan. 2022 11.24 AM skrev Erik Garrison ***@***.***
>:

> Is this via the docker build?
>

**Comment by AndreaGuarracino** [comment] 2022-01-06 10:29
Could you please report exactly all the instructions/steps you are following? Usually, we suggest users to install `pggb` with docker or bioconda.

**Comment by ekg** [comment] 2022-01-06 10:45
It could be caused by building on a system without git. That file should
contain a version string that is pulled from the git tree using the git CLI.

**Comment by grenaud** [comment] 2022-01-06 10:56
thank you for your quick answers! I did:

`git clone https://github.com/ekg/wfmash.git
 cd wfmash/
 mkdir build
 cd build/
 cmake ..
 make -j 10
`

**Comment by ekg** [comment] 2022-01-06 11:09
Looks like it could be a build dependency issue? That file should be
created.

**Comment by grenaud** [comment] 2022-01-06 11:15
Ok I fixed it by changing:
`execute_process(COMMAND bash scripts/generate_git_version.sh ${CMAKE_SOURCE_DIR}/include)
`
to 
`execute_process(COMMAND bash ../scripts/generate_git_version.sh ${CMAKE_SOURCE_DIR}/include)
`

**Comment by AndreaGuarracino** [comment] 2022-01-06 11:16
@grenaud could you please retry with the current master? It should be fixed now.

**Comment by AndreaGuarracino** [comment] 2022-01-06 11:16
> Ok I fixed it by changing: `execute_process(COMMAND bash scripts/generate_git_version.sh ${CMAKE_SOURCE_DIR}/include) ` to `execute_process(COMMAND bash ../scripts/generate_git_version.sh ${CMAKE_SOURCE_DIR}/include) `

Yes, it was exactly a path problem.

**Comment by grenaud** [comment] 2022-01-06 11:33
@AndreaGuarracino  I realized that I raised the issue on the wrong page. It should be on wfmash.

**Comment by AndreaGuarracino** [comment] 2022-01-06 11:36
Do not worry. You would have encountered the same problem in the other components of pggb as well. I'm just fixing them all. Thank you for reporting this issue to us.

**Closed by AndreaGuarracino** 2022-01-06 11:36 UTC
